zigga:
  outputs:
    dev:
      dbname: dbt_db
      host: postgres
      pass: dbt_password
      port: 5432
      schema: dbo
      threads: 1
      type: postgres
      user: dbt_user
  target: dev
